version: '3.8'
services:
  db:
    image: mongo
    ports:
      - 0.0.0.0:27017:27017
  app:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: [ "npm", "run", "start:dev" ]
    depends_on:
      - db