version: '3.8'
services:
  db:
    image: mongo
    ports:
      - ${MONGODB_EXTERNAL_PORT}:27017
  app:
    build: .
    env_file:
      - .env
    ports:
      - ${APP_PORT}:3000
    volumes:
      - .:/app
    command: [ "npm", "run", "start:dev" ]
    depends_on:
      - db